// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByUQt0yME2lalAUTCbMVpNZuYuwyui184',
    appId: '1:827155009823:web:5881284392bec6f8c5a02a',
    messagingSenderId: '827155009823',
    projectId: 'fixupmoto-5e9cb',
    authDomain: 'fixupmoto-5e9cb.firebaseapp.com',
    storageBucket: 'fixupmoto-5e9cb.appspot.com',
    measurementId: 'G-XCKMMHQ76E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDrNV4ICwDtoblSzH0v6OomElB8TKiX5w',
    appId: '1:827155009823:android:2f30102b48ce772bc5a02a',
    messagingSenderId: '827155009823',
    projectId: 'fixupmoto-5e9cb',
    storageBucket: 'fixupmoto-5e9cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyOgNZhUy3nLDAQ-ihr5F-mpPQbUdOsYc',
    appId: '1:827155009823:ios:4612956e78c51756c5a02a',
    messagingSenderId: '827155009823',
    projectId: 'fixupmoto-5e9cb',
    storageBucket: 'fixupmoto-5e9cb.appspot.com',
    iosBundleId: 'com.example.scratchProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyOgNZhUy3nLDAQ-ihr5F-mpPQbUdOsYc',
    appId: '1:827155009823:ios:0d5fa14eed5c779bc5a02a',
    messagingSenderId: '827155009823',
    projectId: 'fixupmoto-5e9cb',
    storageBucket: 'fixupmoto-5e9cb.appspot.com',
    iosBundleId: 'com.example.scratchProject1.RunnerTests',
  );
}
